cc_binary(
  name = 'vision_tuning',
  srcs = ['tuning.cpp'],
  data = ['captured.avi'],
  linkopts = [
    '-lopencv_core',
    '-lopencv_highgui',
    '-lopencv_imgproc',
    '-lopencv_video'
  ]
)
